/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js type tooling and kept in source control so
// CI can type-check the app before the first local dev-server run.
